version: '2'
services:
  web:
    image: ${IMAGE_NAME}
    volumes:
       - "web-data:/opt/sparql-exploration"
    ports:
      - "3000"
    networks:
       - ci
    labels:
      - "traefik.backend=data-driven"
      - "traefik.frontend.rule=Host:data-driven.ci.ukpds.org"

networks:
    ci:
      driver: overlay

volumes:
    web-data:
      driver: local