# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e78cc2da2c1c087b0970a90618b2accdb4edc25f385e53eaa7e9726e6f71b7fdaeadc43ac85e30efa672bc5136a1087fe57618cd2f8593bad1592bd20544e005

test:
  secret_key_base: 1f19f22e2dd3d3e6395e55d1decd8e7078e39596042c5383900dce215dead38615b08a9b4acd85c50fa87e6c2b8fe4d022cdd235f3a3fb59f686cfd53417c8bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
